import type { Prisma } from "../../../lib/generated/prisma/client";

type SceneSeed = Omit<Prisma.SceneCreateInput, "image" | "imageMobile" | "imageSecondary" | "imageSecondaryMobile">;

/**
 * The ten scenes of the home page (brief, section 5). `{nume}` and `{locatie}` are replaced
 * at seed time from config/antrenor.yml. Ball coordinates are fractions of the 16:9 painting.
 */
export function sceneSeeds(vars: { nume: string; locatie: string }): SceneSeed[] {
  const fill = (value: string) => value.replaceAll("{nume}", vars.nume).replaceAll("{locatie}", vars.locatie);

  return [
    {
      key: "deschiderea",
      order: 1,
      indexName: { ro: "Deschiderea", en: "Opening" },
      title: { ro: "Tenisul se învață lovitură cu lovitură.", en: "Tennis is learned one stroke at a time." },
      body: {
        ro: fill(
          "{nume}, antrenor de tenis. Lecții individuale și grupe pentru copii, juniori și adulți, la {locatie}.",
        ),
        en: fill(
          "{nume}, tennis coach. Private lessons and groups for children, juniors and adults, at {locatie}.",
        ),
      },
      ctaLabel: { ro: "Rezervă o lecție", en: "Book a lesson" },
      ctaHref: "/rezervare",
      imageAlt: {
        ro: "Pictură: un tânăr în haine renascentiste ocru, din profil, ține o minge de tenis aurie și o rachetă veche de lemn.",
        en: "Painting: a young man in an ochre Renaissance doublet, in profile, holding a gold tennis ball and an old wooden racquet.",
      },
      artKey: "01-deschiderea",
      textPosDesktop: "STANGA_CENTRU",
      textPosMobile: "CENTRU_JOS",
      tone: "INCHIS",
      veil: false,
      ballX: 0.64,
      ballY: 0.5,
      ballSize: 0.045,
      transition: "ZOOM_LENT",
    },
    {
      key: "impreuna",
      order: 2,
      indexName: { ro: "Împreună", en: "Together" },
      title: { ro: "Eu aduc metoda. Tu aduci răbdarea.", en: "I bring the method. You bring the patience." },
      body: {
        ro: "Progresul se vede de la o săptămână la alta, și îl urmărim împreună.",
        en: "Progress shows from one week to the next, and we follow it together.",
      },
      imageAlt: {
        ro: "Pictură: o mână matură și o mână tânără își trec o minge de tenis aurie.",
        en: "Painting: an older hand and a young hand passing a gold tennis ball between them.",
      },
      artKey: "02-impreuna",
      textPosDesktop: "STANGA_JOS",
      textPosMobile: "CENTRU_JOS",
      tone: "INCHIS",
      ballX: 0.5,
      ballY: 0.42,
      ballSize: 0.05,
      transition: "ZOOM_MINGE",
    },
    {
      key: "filozofia",
      order: 3,
      indexName: { ro: "Filozofia", en: "Philosophy" },
      title: { ro: "Un joc bun e făcut din lucruri mici.", en: "A good game is made of small things." },
      body: {
        ro: "Priza. Pasul de ajustare. Momentul impactului. Respirația dintre puncte. Pe ele se sprijină tot restul, și cu ele începem.",
        en: "The grip. The adjustment step. The moment of contact. The breath between points. Everything else rests on them, and that is where we start.",
      },
      imageAlt: {
        ro: "Cer ultramarin cu nori albi; o minge aurie se compune din puncte.",
        en: "Ultramarine sky with white clouds; a gold ball forms out of dots.",
      },
      artKey: "03-cer",
      textPosDesktop: "STANGA_CENTRU",
      textPosMobile: "CENTRU_JOS",
      tone: "DESCHIS",
      ballX: 0.6,
      ballY: 0.44,
      ballSize: 0.07,
      transition: "NORI",
    },
    {
      key: "metoda",
      order: 4,
      indexName: { ro: "Metoda", en: "Method" },
      title: { ro: "Cum lucrăm", en: "How we work" },
      body: {
        ro: [
          "1. **Evaluare.** La prima lecție vedem tehnica, mișcarea și ce îți dorești de la tenis.",
          "2. **Plan.** Obiective pe 8–12 săptămâni, scrise și împărtășite cu tine sau cu părinții.",
          "3. **Antrenament.** Fiecare lecție are un singur obiectiv clar.",
          "4. **Verificare.** Joc, meci și analiză video, ca să vezi singur progresul.",
        ].join("\n"),
        en: [
          "1. **Assessment.** In the first lesson we look at technique, movement and what you want from tennis.",
          "2. **Plan.** Goals for 8–12 weeks, written down and shared with you or with the parents.",
          "3. **Training.** Every lesson has one clear goal.",
          "4. **Review.** Play, match and video analysis, so you can see the progress yourself.",
        ].join("\n"),
      },
      imageAlt: {
        ro: "Frescă: meșteri pe schele de lemn construiesc o minge aurie uriașă; apoi un personaj desfășoară un pergament cu planul unui teren.",
        en: "Fresco: craftsmen on wooden scaffolding build a giant gold ball; then a figure unrolls a parchment with the plan of a court.",
      },
      artKey: "04-schele",
      artKeySecondary: "04b-pergament",
      textPosDesktop: "STANGA_CENTRU",
      textPosMobile: "CENTRU_JOS",
      tone: "INCHIS",
      veil: true,
      ballX: 0.66,
      ballY: 0.46,
      ballSize: 0.24,
      transition: "PERGAMENT",
    },
    {
      key: "programe",
      order: 5,
      indexName: { ro: "Programe", en: "Programmes" },
      title: { ro: "Pentru cine", en: "Who it is for" },
      body: { ro: "", en: "" },
      ctaLabel: { ro: "Toate programele", en: "All programmes" },
      ctaHref: "/programe",
      imageAlt: {
        ro: "Picturi mici, câte una pentru fiecare program, așezate pe pergament.",
        en: "Small paintings, one for each programme, laid out on parchment.",
      },
      artKey: "textura-pergament",
      textPosDesktop: "STANGA_SUS",
      textPosMobile: "CENTRU_SUS",
      tone: "INCHIS",
      ballX: 0.2,
      ballY: 0.4,
      ballSize: 0.03,
      transition: "DIZOLVARE",
    },
    {
      key: "terenul",
      order: 6,
      indexName: { ro: "Terenul", en: "The court" },
      title: { ro: "Unde jucăm", en: "Where we play" },
      body: { ro: "", en: "" },
      ctaLabel: { ro: "Vezi facilitățile", en: "See the facilities" },
      ctaHref: "/facilitati",
      imageAlt: {
        ro: "Schiță sepia a unui teren de tenis văzut de sus, care devine o curte cu mozaic în tonuri de zgură.",
        en: "Sepia sketch of a tennis court seen from above, turning into a mosaic courtyard in clay tones.",
      },
      artKey: "06-schita-teren",
      artKeySecondary: "06b-mozaic",
      textPosDesktop: "DREAPTA_CENTRU",
      textPosMobile: "CENTRU_JOS",
      tone: "INCHIS",
      ballX: 0.5,
      ballY: 0.5,
      ballSize: 0.022,
      transition: "DIZOLVARE",
    },
    {
      key: "prima-lectie",
      order: 7,
      indexName: { ro: "Prima lecție", en: "First lesson" },
      title: { ro: "Prima lecție este o evaluare.", en: "The first lesson is an assessment." },
      body: {
        ro: "Vedem unde ești și stabilim unde vrei să ajungi. Fără abonament obligatoriu.",
        en: "We see where you are and agree on where you want to get to. No subscription required.",
      },
      ctaLabel: { ro: "Vezi prețurile", en: "See the prices" },
      ctaHref: "/preturi",
      imageAlt: {
        ro: "Curtea-mozaic văzută de sus, într-un cadru mai larg, cu mingea aurie în centru.",
        en: "The mosaic courtyard seen from above in a wider frame, with the gold ball at its centre.",
      },
      artKey: "06b-mozaic",
      textPosDesktop: "STANGA_CENTRU",
      textPosMobile: "CENTRU_JOS",
      tone: "INCHIS",
      ballX: 0.5,
      ballY: 0.5,
      ballSize: 0.022,
      transition: "MASCA_PENSULA",
    },
    {
      key: "locurile",
      order: 8,
      indexName: { ro: "Locuri", en: "Places" },
      title: { ro: "Lucrez cu puțini elevi.", en: "I work with few students." },
      body: {
        ro: "Ca fiecare să primească atenție reală, numărul de locuri e limitat.",
        en: "So that everyone gets real attention, the number of places is limited.",
      },
      extra: {
        available: { ro: "Locuri libere în {luna}: {n}", en: "Places left in {luna}: {n}" },
        full: {
          ro: "Luna aceasta e completă. Poți intra pe lista de așteptare.",
          en: "This month is full. You can join the waiting list.",
        },
        waitlistLabel: { ro: "Intră pe lista de așteptare", en: "Join the waiting list" },
      },
      imageAlt: {
        ro: "Pictură: o tânără în veșmânt albastru-pal culege mingi aurii dintr-un pom plantat într-un vas de teracotă.",
        en: "Painting: a young woman in a pale blue robe picks gold balls from a small tree in a terracotta urn.",
      },
      artKey: "08-pom",
      textPosDesktop: "STANGA_CENTRU",
      textPosMobile: "CENTRU_JOS",
      tone: "INCHIS",
      ballX: 0.72,
      ballY: 0.3,
      ballSize: 0.03,
      transition: "CURCUBEU",
    },
    {
      key: "intrebari",
      order: 9,
      indexName: { ro: "Întrebări", en: "Questions" },
      title: { ro: "Întrebat înainte de prima lecție", en: "Asked before the first lesson" },
      body: { ro: "", en: "" },
      ctaLabel: { ro: "Toate întrebările", en: "All questions" },
      ctaHref: "/intrebari",
      imageAlt: {
        ro: "O minge aurie sub un curcubeu, apoi ramuri dese cu mingi aurii printre frunze.",
        en: "A gold ball under a rainbow, then dense branches with gold balls among the leaves.",
      },
      artKey: "09-curcubeu",
      artKeySecondary: "09b-ramuri",
      textPosDesktop: "CENTRU",
      textPosMobile: "CENTRU",
      tone: "INCHIS",
      veil: true,
      ballX: 0.5,
      ballY: 0.52,
      ballSize: 0.05,
      transition: "NOAPTE",
    },
    {
      key: "constelatia",
      order: 10,
      indexName: { ro: "Constelația", en: "Constellation" },
      title: { ro: "Următoarea lovitură e a ta.", en: "The next shot is yours." },
      body: {
        ro: "Alege programul și vezi primele ore libere.",
        en: "Choose a programme and see the first free times.",
      },
      imageAlt: {
        ro: "Cer de noapte ultramarin; o figură în alb arată spre o constelație care desenează traiectoria unei mingi peste un teren.",
        en: "Ultramarine night sky; a figure in white points at a constellation tracing the arc of a ball over a court.",
      },
      artKey: "10-constelatie",
      textPosDesktop: "DREAPTA_CENTRU",
      textPosMobile: "CENTRU_JOS",
      tone: "DESCHIS",
      ballX: 0.42,
      ballY: 0.26,
      ballSize: 0.018,
      transition: "DIZOLVARE",
    },
  ];
}
