# Generated by Django 5.2.17 on 2026-09-27 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_grid_and_duration_checks"),
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "registration_code",
                    models.CharField(blank=True, max_length=20, verbose_name="CUI"),
                ),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Gol = reducerea implicită din configurare (Q35).",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "cont corporate",
                "verbose_name_plural": "conturi corporate",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "Lunar"),
                            ("quarterly", "Trimestrial"),
                            ("annual", "Anual"),
                        ],
                        max_length=10,
                    ),
                ),
                ("starts_on", models.DateField()),
                (
                    "ends_on",
                    models.DateField(
                        help_text="Exclusiv; se prelungește cu zilele de înghețare (R-086)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Așteaptă plata"),
                            ("active", "Activ"),
                            ("cancelled", "Anulat"),
                        ],
                        default="pending_payment",
                        max_length=16,
                    ),
                ),
                (
                    "custom",
                    models.BooleanField(
                        default=False, help_text="Intensitate „La cerere” (Q12)."
                    ),
                ),
                (
                    "price_total",
                    models.PositiveIntegerField(verbose_name="preț total (bani)"),
                ),
                ("price_breakdown", models.JSONField(default=dict)),
                ("price_provisional", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "corporate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.corporateaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "abonament",
                "verbose_name_plural": "abonamente",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("padel", "Padel"),
                            ("tennis", "Tenis"),
                            ("pilates", "Pilates (Reformer)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sessions_per_month", models.PositiveSmallIntegerField()),
                (
                    "peak_allowed",
                    models.BooleanField(
                        help_text="R-087: Start (sub prag) nu intră în orele de vârf."
                    ),
                ),
                (
                    "monthly_price",
                    models.PositiveIntegerField(verbose_name="preț pe lună (bani)"),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "sport din abonament",
                "verbose_name_plural": "sporturi din abonament",
                "ordering": ["sport"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionFreeze",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField(help_text="Exclusiv.")),
                ("created_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freezes",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "înghețare",
                "verbose_name_plural": "înghețări",
                "ordering": ["starts_on"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionMakeup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expires_on", models.DateField()),
                ("created_at", models.DateTimeField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makeups",
                        to="subscriptions.subscriptioncomponent",
                    ),
                ),
            ],
            options={
                "verbose_name": "sesiune de recuperare",
                "verbose_name_plural": "sesiuni de recuperare",
                "ordering": ["expires_on", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("padel", "Padel"),
                            ("tennis", "Tenis"),
                            ("pilates", "Pilates (Reformer)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sessions_per_month", models.PositiveSmallIntegerField()),
                (
                    "monthly_price",
                    models.PositiveIntegerField(verbose_name="preț pe lună (bani)"),
                ),
                (
                    "marker",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmat de proprietar"),
                            ("default", "Valoare tehnică implicită"),
                            ("to_confirm", "DE_CONFIRMAT"),
                            ("to_set", "DE_STABILIT"),
                        ],
                        default="to_set",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarif abonament",
                "verbose_name_plural": "tarife abonamente",
                "ordering": ["sport", "sessions_per_month"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionUse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cycle",
                    models.PositiveSmallIntegerField(
                        help_text="Luna abonamentului (0 = prima)."
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_use",
                        to="bookings.booking",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uses",
                        to="subscriptions.subscriptioncomponent",
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_use",
                        to="bookings.classenrollment",
                    ),
                ),
                (
                    "makeup",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="use",
                        to="subscriptions.subscriptionmakeup",
                    ),
                ),
            ],
            options={
                "verbose_name": "sesiune folosită",
                "verbose_name_plural": "sesiuni folosite",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CorporateMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField()),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="subscriptions.corporateaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "angajat corporate",
                "verbose_name_plural": "angajați corporate",
                "ordering": ["added_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=("account", "user"),
                        name="corporate_member_once",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__gt", models.F("starts_on"))),
                name="subscription_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptioncomponent",
            constraint=models.UniqueConstraint(
                fields=("subscription", "sport"), name="subscription_sport_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionrate",
            constraint=models.UniqueConstraint(
                fields=("location", "sport", "sessions_per_month"),
                name="subscription_rate_unique",
            ),
        ),
    ]
