# Generated by Django 5.2.17 on 2026-09-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corporateaccount",
            name="discount_percent",
        ),
    ]
