# Generated by Django 5.2.17 on 2026-09-26 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("league_kiosk", "Chioșc Ligă"),
                            ("payments_kiosk", "Chioșc Plăți"),
                            ("screen", "Ecran (teren / lobby)"),
                            ("cafe_display", "Afișaj cafenea"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "public_key",
                    models.TextField(
                        blank=True,
                        help_text="Cheia publică Ed25519 a Hardware Bridge (Etapa 7).",
                    ),
                ),
                (
                    "certificate_fingerprint",
                    models.CharField(blank=True, max_length=128),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "dispozitiv",
                "verbose_name_plural": "dispozitive",
                "ordering": ["location__name", "kind", "name"],
            },
        ),
    ]
