# Generated by Django 5.2.17 on 2026-09-27 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        ("locations", "0002_romanian_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="activ"),
        ),
        migrations.AlterField(
            model_name="device",
            name="kind",
            field=models.CharField(
                choices=[
                    ("league_kiosk", "Chioșc Ligă"),
                    ("payments_kiosk", "Chioșc Plăți"),
                    ("screen", "Ecran (teren / lobby)"),
                    ("cafe_display", "Afișaj cafenea"),
                ],
                max_length=20,
                verbose_name="tip",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="ultimul semnal"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="locations.location",
                verbose_name="locație",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(max_length=120, verbose_name="nume"),
        ),
    ]
