# Generated by Django 5.2.17 on 2026-09-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_romanian_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="enrolled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="înrolat la"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="token_hash",
            field=models.CharField(
                blank=True, help_text="SHA-256 al tokenului.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="certificate_fingerprint",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 al certificatului client (mTLS).",
                max_length=128,
            ),
        ),
    ]
