# Generated by Django 5.2.17 on 2026-09-29 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_device_token"),
        ("locations", "0002_romanian_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Doar pentru ecranul unui teren (§8.5); fără teren: ecran de lobby.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="screens",
                to="locations.resource",
                verbose_name="teren",
            ),
        ),
    ]
