# Generated by Django 5.2.17 on 2026-10-06 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TextOverride",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "key",
                    models.CharField(
                        help_text="web.… (the catalogue's path)", max_length=200
                    ),
                ),
                ("language", models.CharField(max_length=2)),
                ("draft", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "published",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField()),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "text schimbat",
                "verbose_name_plural": "texte schimbate",
                "ordering": ["key", "language"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "language"), name="text_override_once"
                    )
                ],
            },
        ),
    ]
