# Generated by Django 5.2.17 on 2026-09-26 20:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        max_length=60,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                                "Doar litere mici, cifre și cratime.",
                                code="invalid_slug",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(blank=True, max_length=250)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "locație",
                "verbose_name_plural": "locații",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("padel_court", "Teren de padel"),
                            ("tennis_court", "Teren de tenis"),
                            ("pilates_studio", "Sală de pilates"),
                            ("reformer", "Aparat Reformer"),
                            ("event_room", "Sală de evenimente"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        max_length=60,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                                "Doar litere mici, cifre și cratime.",
                                code="invalid_slug",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="locations.location",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="locations.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "resursă",
                "verbose_name_plural": "resurse",
                "ordering": ["location__name", "kind", "sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "slug"), name="resource_slug_per_location"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("capacity__isnull", True),
                            ("capacity__gte", 1),
                            _connector="OR",
                        ),
                        name="resource_capacity_positive",
                    ),
                ],
            },
        ),
    ]
