# Generated by Django 5.2.17 on 2026-09-27 02:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(blank=True, max_length=250, verbose_name="adresă"),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="localitate"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="activă"),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=120, verbose_name="nume"),
        ),
        migrations.AlterField(
            model_name="location",
            name="slug",
            field=models.CharField(
                max_length=60,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                        "Doar litere mici, cifre și cratime.",
                        code="invalid_slug",
                    )
                ],
                verbose_name="identificator",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="attributes",
            field=models.JSONField(blank=True, default=dict, verbose_name="atribute"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="capacitate"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="activă"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="kind",
            field=models.CharField(
                choices=[
                    ("padel_court", "Teren de padel"),
                    ("tennis_court", "Teren de tenis"),
                    ("pilates_studio", "Sală de pilates"),
                    ("reformer", "Aparat Reformer"),
                    ("event_room", "Sală de evenimente"),
                ],
                max_length=30,
                verbose_name="tip",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resources",
                to="locations.location",
                verbose_name="locație",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.CharField(max_length=120, verbose_name="nume"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="locations.resource",
                verbose_name="resursă-părinte",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="slug",
            field=models.CharField(
                max_length=60,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                        "Doar litere mici, cifre și cratime.",
                        code="invalid_slug",
                    )
                ],
                verbose_name="identificator",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="ordine"),
        ),
    ]
