# Generated by Django 5.2.17 on 2026-09-27 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("legal", "0002_append_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                ("email_sha256", models.CharField(max_length=64, unique=True)),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, verbose_name="nume"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="telefon"),
                ),
                (
                    "interests",
                    models.JSONField(blank=True, default=list, verbose_name="interese"),
                ),
                (
                    "language",
                    models.CharField(default="ro", max_length=5, verbose_name="limba"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=60, verbose_name="sursa"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Neconfirmat"),
                            ("confirmed", "Confirmat"),
                            ("withdrawn", "Dezabonat"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="stare",
                    ),
                ),
                ("notice_sha256", models.CharField(max_length=64)),
                ("consent_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("consent_user_agent", models.CharField(blank=True, max_length=300)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="înscris la"),
                ),
                ("confirmation_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="confirmat la"
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dezabonat la"
                    ),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="legal.legaldocument",
                        verbose_name="nota de informare",
                    ),
                ),
            ],
            options={
                "verbose_name": "înscriere pe lista de așteptare",
                "verbose_name_plural": "lista de așteptare",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "withdrawn"),
                            ("email__isnull", False),
                            _connector="OR",
                        ),
                        name="waitlist_email_required_unless_withdrawn",
                    )
                ],
            },
        ),
    ]
