# Generated by Django 5.2.17 on 2026-09-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waitlist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waitlistentry",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="waitlistentry",
            name="phone",
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Începător"),
                    ("intermediate", "Intermediar"),
                    ("advanced", "Avansat"),
                    ("competitive", "Competiție"),
                ],
                max_length=15,
                verbose_name="nivel de joc",
            ),
        ),
    ]
