# Generated by Django 5.2.17 on 2026-09-27 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Conținutul codului QR (aleatoriu).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Număr scurt, tipărit pe card.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activ"), ("revoked", "Blocat")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "wallet_auth_token",
                    models.CharField(
                        help_text="Cheia serviciului Apple Wallet.", max_length=64
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                (
                    "updated_at",
                    models.DateTimeField(
                        help_text="Ultima schimbare vizibilă pe card (R-023)."
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.CharField(blank=True, max_length=250)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "card de membru",
                "verbose_name_plural": "carduri de membru",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="AppleDeviceRegistration",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("device_library_id", models.CharField(max_length=128)),
                ("push_token", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apple_registrations",
                        to="cards.membercard",
                    ),
                ),
            ],
            options={
                "verbose_name": "dispozitiv Apple Wallet",
                "verbose_name_plural": "dispozitive Apple Wallet",
            },
        ),
        migrations.CreateModel(
            name="PhysicalCardRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("new_member", "Membru nou"),
                            ("reissue", "Reemitere (card pierdut sau deteriorat)"),
                            ("diamond", "Promovare în Diamant (R-024)"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "emblem",
                    models.CharField(
                        blank=True,
                        help_text="R-024, Q1: emblema aleasă.",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "De tipărit"),
                            ("printed", "Tipărit"),
                            ("handed_over", "Predat"),
                            ("cancelled", "Anulat"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                ("handed_over_at", models.DateTimeField(blank=True, null=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_requests",
                        to="cards.membercard",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "card de tipărit",
                "verbose_name_plural": "carduri de tipărit",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="membercard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user",),
                name="one_active_card",
            ),
        ),
        migrations.AddConstraint(
            model_name="appledeviceregistration",
            constraint=models.UniqueConstraint(
                fields=("card", "device_library_id"), name="apple_registration_once"
            ),
        ),
    ]
