# Generated by Django 5.2.17 on 2026-09-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physicalcardrequest",
            name="reason",
            field=models.CharField(
                choices=[
                    ("new_member", "Membru nou"),
                    ("reissue", "Reemitere (card pierdut sau deteriorat)"),
                    ("diamond", "Promovare în Diamant (R-024)"),
                    ("king", "Rege al Junglei (§6.12)"),
                ],
                max_length=12,
            ),
        ),
    ]
