# Generated by Django 5.2.17 on 2026-10-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("job", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("ok", models.BooleanField(help_text="empty while it runs", null=True)),
                ("output", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "rulare programată",
                "verbose_name_plural": "rulări programate",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "-started_at"], name="scheduler_j_job_2c7e36_idx"
                    )
                ],
            },
        ),
    ]
