# Generated by Django 5.2.17 on 2026-09-27 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("arrival", "Check-in la sosire"),
                            ("court_entry", "Intrare pe teren"),
                            ("class_entry", "Intrare la clasă"),
                        ],
                        max_length=15,
                    ),
                ),
                ("scanned_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "scanare",
                "verbose_name_plural": "scanări",
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_role", models.CharField(blank=True, max_length=20)),
                ("kind", models.CharField(max_length=40)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "notificare pentru personal",
                "verbose_name_plural": "notificări pentru personal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(max_length=250)),
                ("no_show_count", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField()),
                ("lifted_at", models.DateTimeField(blank=True, null=True)),
                ("lift_reason", models.CharField(blank=True, max_length=250)),
                (
                    "lifted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "blocare rezervări",
                "verbose_name_plural": "blocări rezervări",
                "ordering": ["-created_at"],
            },
        ),
    ]
