# Generated by Django 5.2.17 on 2026-09-27 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("bookings", "0001_initial"),
        ("devices", "0002_romanian_labels"),
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scans",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scans",
                to="bookings.classenrollment",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="locations.location"
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.resource",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffnotice",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="locations.location"
            ),
        ),
        migrations.AddField(
            model_name="staffnotice",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingrestriction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lifted_at__isnull", True)),
                fields=("user",),
                name="one_active_block",
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(
                fields=["user", "scanned_at"], name="attendance__user_id_e3cc8e_idx"
            ),
        ),
    ]
