# Generated by Django 5.2.17 on 2026-09-27 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0002_romanian_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_kind",
                    models.CharField(
                        choices=[
                            ("padel_court", "Teren de padel"),
                            ("tennis_court", "Teren de tenis"),
                            ("pilates_studio", "Sală de pilates"),
                            ("reformer", "Aparat Reformer"),
                            ("event_room", "Sală de evenimente"),
                        ],
                        max_length=30,
                        verbose_name="resursă",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("rental", "Închiriere"),
                            ("lesson", "Lecție cu antrenor"),
                            ("class", "Clasă"),
                            ("event", "Eveniment"),
                        ],
                        max_length=20,
                        verbose_name="produs",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("all", "Tot anul"),
                            ("summer", "Vară"),
                            ("winter", "Iarnă"),
                        ],
                        default="all",
                        max_length=10,
                        verbose_name="sezon",
                    ),
                ),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("peak", "Vârf"),
                            ("semi_peak", "Semi-vârf"),
                            ("off_peak", "În afara vârfului"),
                        ],
                        max_length=10,
                        verbose_name="bandă orară",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("standard", "Neabonat"),
                            ("member", "Abonat"),
                            ("corporate", "Corporate"),
                        ],
                        default="standard",
                        max_length=12,
                        verbose_name="tip client",
                    ),
                ),
                (
                    "amount_per_half_hour",
                    models.PositiveIntegerField(
                        verbose_name="preț pe 30 de minute (bani)"
                    ),
                ),
                (
                    "marker",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmat de proprietar"),
                            ("default", "Valoare tehnică implicită"),
                            ("to_confirm", "DE_CONFIRMAT"),
                            ("to_set", "DE_STABILIT"),
                        ],
                        default="to_set",
                        max_length=12,
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="notă"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_rates",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarif",
                "verbose_name_plural": "tarife",
                "ordering": [
                    "location",
                    "resource_kind",
                    "product",
                    "season",
                    "band",
                    "customer_type",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "location",
                            "resource_kind",
                            "product",
                            "season",
                            "band",
                            "customer_type",
                        ),
                        name="price_rate_unique_combination",
                    )
                ],
            },
        ),
    ]
