# Generated by Django 5.2.17 on 2026-10-01 01:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.URLField(max_length=1000, unique=True)),
                ("p256dh", models.CharField(max_length=200)),
                ("auth", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "abonare push",
                "verbose_name_plural": "abonările push",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event", models.CharField(max_length=40)),
                ("channel", models.CharField(max_length=8)),
                ("language", models.CharField(default="ro", max_length=2)),
                ("key", models.CharField(max_length=200, unique=True)),
                ("context", models.JSONField(default=dict)),
                ("send_after", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "De trimis"),
                            ("sent", "Trimisă"),
                            ("failed", "Netrimisă"),
                            ("skipped", "Nu s-a trimis (oprită sau fără canal)"),
                        ],
                        default="queued",
                        max_length=8,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notificare",
                "verbose_name_plural": "notificări",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "send_after"], name="notification_due"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=16)),
                ("channel", models.CharField(max_length=8)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_choices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "category", "channel"),
                        name="notification_choice_once",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=40)),
                ("channel", models.CharField(max_length=8)),
                ("language", models.CharField(max_length=2)),
                (
                    "subject",
                    models.CharField(
                        help_text="Subiectul emailului sau titlul notificării.",
                        max_length=160,
                    ),
                ),
                ("body", models.TextField(max_length=5000)),
                ("updated_at", models.DateTimeField()),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "șablon de notificare",
                "verbose_name_plural": "șabloanele notificărilor",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "channel", "language"),
                        name="notification_template_once",
                    )
                ],
            },
        ),
    ]
