# Generated by Django 5.2.17 on 2026-09-27 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="referral_code",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("code", models.CharField(max_length=12, unique=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "cod de recomandare",
                "verbose_name_plural": "coduri de recomandare",
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Așteaptă primul abonament"),
                            ("rewarded", "Vouchere acordate"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("rewarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referred",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recomandare",
                "verbose_name_plural": "recomandări",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hour", "O oră gratuită de padel"),
                            ("amount", "Sumă fixă"),
                            ("percent", "Reducere procentuală"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        help_text="minute (oră), bani (sumă) sau procent"
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("booking", "Rezervare de teren"),
                            ("subscription", "Abonament"),
                            ("any", "Orice"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "allowed_bands",
                    models.JSONField(
                        blank=True, default=list, help_text="Gol = orice bandă (Q32)."
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(help_text="Inclusiv.")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("referral", "Adu un prieten"),
                            ("reward", "Recompensă de sezon"),
                            ("manual", "Emis de manager"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activ"),
                            ("redeemed", "Folosit"),
                            ("cancelled", "Anulat"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("redeemed_subject", models.CharField(blank=True, max_length=80)),
                (
                    "holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "voucher",
                "verbose_name_plural": "vouchere",
                "ordering": ["-issued_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "percent"), _negated=True),
                            ("value__lte", 100),
                            _connector="OR",
                        ),
                        name="voucher_percent_le_100",
                    )
                ],
            },
        ),
    ]
