# Generated by Django 5.2.17 on 2026-09-29 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_grid_and_duration_checks"),
        ("devices", "0004_screen_court"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourtLineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_a",
                    models.JSONField(
                        default=list, help_text="Id-urile jucătorilor din prima echipă."
                    ),
                ),
                (
                    "team_b",
                    models.JSONField(
                        default=list,
                        help_text="Id-urile jucătorilor din a doua echipă.",
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup",
                        to="bookings.booking",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="devices.device",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "echipele de pe teren",
                "verbose_name_plural": "echipele de pe teren",
            },
        ),
    ]
