# Generated by Django 5.2.17 on 2026-09-28 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_deleted_accounts"),
        ("devices", "0003_device_token"),
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KioskPin",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("pin_hash", models.CharField(max_length=200)),
                ("failures", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "PIN de chioșc",
                "verbose_name_plural": "PIN-uri de chioșc",
            },
        ),
        migrations.CreateModel(
            name="CashOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("refill", "Alimentare rest"),
                            ("empty", "Golire casetă"),
                            ("count", "Numărare"),
                            ("day_close", "Închidere de zi (raport Z)"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "requested",
                    models.JSONField(
                        blank=True, default=dict, help_text="Ce a cerut personalul"
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, help_text="Ce a raportat aparatul"
                    ),
                ),
                (
                    "amount",
                    models.BigIntegerField(
                        blank=True, help_text="bani (după aparat)", null=True
                    ),
                ),
                (
                    "ledger_amount",
                    models.BigIntegerField(
                        blank=True,
                        help_text="bani: ce arată registrul pentru acest aparat",
                        null=True,
                    ),
                ),
                (
                    "difference",
                    models.BigIntegerField(
                        blank=True, help_text="aparat − registru", null=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="devices.device",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "operațiune de casă",
                "verbose_name_plural": "operațiuni de casă",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Coș (fără bani)"),
                            ("collecting", "Se primesc bani"),
                            ("paid", "Plătit, se dă restul"),
                            ("settled", "Încheiat"),
                            ("cancelled", "Anulat"),
                            ("interrupted", "Întrerupt (reconciliat)"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                (
                    "change_mode",
                    models.CharField(
                        choices=[
                            ("normal", "Cu rest"),
                            ("exact", "Doar suma exactă"),
                            (
                                "credit",
                                "Restul pe care aparatul nu-l poate da intră în cont (cu acordul clientului)",
                            ),
                        ],
                        default="normal",
                        max_length=8,
                    ),
                ),
                ("amount_due", models.PositiveBigIntegerField(help_text="bani")),
                ("inserted", models.PositiveBigIntegerField(default=0)),
                ("dispensed", models.PositiveBigIntegerField(default=0)),
                ("credited", models.PositiveBigIntegerField(default=0)),
                ("fiscal_receipt", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField()),
                ("collecting_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="devices.device",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "plată la chioșc",
                "verbose_name_plural": "plăți la chioșc",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        help_text="ID-ul evenimentului, din Bridge",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cash.started", "Plată începută"),
                            ("cash.accepted", "Bancnotă primită"),
                            ("cash.dispensed", "Rest dat"),
                            ("cash.closed", "Plată încheiată"),
                            ("cash.interrupted", "Plată întreruptă (cădere de curent)"),
                            ("cash.refilled", "Rest alimentat"),
                            ("cash.emptied", "Casetă golită"),
                            ("cash.counted", "Numărare"),
                            ("fiscal.printed", "Bon fiscal tipărit"),
                            ("fiscal.z", "Raport Z"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.BigIntegerField(default=0)),
                (
                    "envelope",
                    models.JSONField(help_text="Mesajul semnat, așa cum a venit"),
                ),
                ("happened_at", models.DateTimeField(help_text="Ora de pe aparat")),
                ("received_at", models.DateTimeField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="devices.device",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="checkout.cashoperation",
                    ),
                ),
                (
                    "checkout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="checkout.checkout",
                    ),
                ),
            ],
            options={
                "verbose_name": "eveniment de numerar",
                "verbose_name_plural": "evenimente de numerar",
                "ordering": ["happened_at", "received_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckoutItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("booking", "Rezervare (sau partea din ea)"),
                            ("enrollment", "Loc la clasă"),
                            ("subscription", "Abonament"),
                            ("tournament_entry", "Taxă de turneu"),
                            ("cafe", "Cafenea"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject_id", models.UUIDField(blank=True, null=True)),
                ("amount", models.PositiveBigIntegerField(help_text="bani")),
                ("description", models.CharField(max_length=250)),
                ("cafe_lines", models.JSONField(blank=True, default=list)),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="checkout.checkout",
                    ),
                ),
            ],
            options={
                "verbose_name": "ce se plătește",
                "verbose_name_plural": "ce se plătește",
                "ordering": ["position"],
            },
        ),
        migrations.AddConstraint(
            model_name="checkout",
            constraint=models.CheckConstraint(
                condition=models.Q(("dispensed__lte", models.F("inserted"))),
                name="checkout_change_le_inserted",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkoutitem",
            constraint=models.UniqueConstraint(
                fields=("checkout", "position"), name="checkout_item_position"
            ),
        ),
    ]
