# Generated by Django 5.2.17 on 2026-09-26 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("terms", "Termeni și condiții"),
                            ("privacy", "Politica de confidențialitate"),
                            ("league_gdpr", "Acordul GDPR al ligii"),
                            (
                                "waitlist_notice",
                                "Nota de informare pentru lista de așteptare",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("language", models.CharField(max_length=5)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("sha256", models.CharField(max_length=64)),
                ("is_demo", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField()),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "document legal",
                "verbose_name_plural": "documente legale",
                "ordering": ["kind", "language", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "version", "language"),
                        name="legal_document_version_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("granted", "Acordat"), ("withdrawn", "Retras")],
                        max_length=10,
                    ),
                ),
                ("text_sha256", models.CharField(max_length=64)),
                ("language", models.CharField(max_length=5)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="devices.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents",
                        to="legal.legaldocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "acord",
                "verbose_name_plural": "acorduri",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
    ]
