# Generated by Django 5.2.17 on 2026-09-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0002_append_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldocument",
            name="kind",
            field=models.CharField(
                choices=[
                    ("terms", "Termeni și condiții"),
                    ("privacy", "Politica de confidențialitate"),
                    ("league_gdpr", "Acordul GDPR al ligii"),
                    ("waitlist_notice", "Nota de informare pentru lista de așteptare"),
                    ("refunds", "Politica de anulare și rambursare"),
                    ("cookies", "Politica de cookies"),
                ],
                max_length=30,
            ),
        ),
    ]
