# Generated by Django 5.2.17 on 2026-09-30 23:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Adresa articolului: /blog/<slug>.", max_length=80
                    ),
                ),
                ("title_ro", models.CharField(max_length=140)),
                ("title_en", models.CharField(max_length=140)),
                ("summary_ro", models.CharField(max_length=300)),
                ("summary_en", models.CharField(max_length=300)),
                ("body_ro", models.TextField(max_length=40000)),
                ("body_en", models.TextField(max_length=40000)),
                ("published", models.BooleanField(default=False)),
                ("first_published_at", models.DateTimeField(blank=True, null=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "articol",
                "verbose_name_plural": "articolele blogului",
                "ordering": ["-first_published_at", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "slug"), name="article_slug_per_location"
                    )
                ],
            },
        ),
    ]
