# Generated by Django 5.2.17 on 2026-09-27 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_deleted_accounts"),
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaguePlayer",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="league_player",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "În ligă"), ("withdrawn", "Retras")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField()),
                ("left_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "jucător de ligă",
                "verbose_name_plural": "jucători de ligă",
            },
        ),
        migrations.CreateModel(
            name="LeagueSeason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=120)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planificat"),
                            ("active", "În desfășurare"),
                            ("closed", "Încheiat"),
                        ],
                        default="planned",
                        max_length=10,
                    ),
                ),
                (
                    "is_calibration",
                    models.BooleanField(
                        default=False, help_text="Sezonul 0: fără premii (Q27)."
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Valorile ligii fixate la începutul sezonului.",
                    ),
                ),
                (
                    "base_state",
                    models.JSONField(
                        blank=True, help_text="Starea ligii la început.", null=True
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="league_seasons",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "sezon",
                "verbose_name_plural": "sezoane",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="LeagueSnapshot",
            fields=[
                (
                    "season",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="snapshot",
                        serialize=False,
                        to="league.leagueseason",
                    ),
                ),
                ("state", models.JSONField()),
                ("last_event_id", models.BigIntegerField(default=0)),
                ("last_at", models.DateTimeField(blank=True, null=True)),
                ("computation", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "starea ligii",
                "verbose_name_plural": "starea ligii",
            },
        ),
        migrations.CreateModel(
            name="LeagueEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("register", "Jucător înscris"),
                            ("match", "Meci aplicat"),
                            ("bonus", "Bonus LP (turneu)"),
                            ("decay", "Decay zilnic"),
                            ("cancel", "Meci anulat"),
                        ],
                        max_length=10,
                    ),
                ),
                ("at", models.DateTimeField()),
                (
                    "ref",
                    models.CharField(
                        help_text="Meciul sau jucătorul la care se referă.",
                        max_length=80,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("actor", models.JSONField(default=dict)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField()),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="league.leagueseason",
                    ),
                ),
            ],
            options={
                "verbose_name": "eveniment de ligă",
                "verbose_name_plural": "evenimente de ligă",
                "ordering": ["at", "id"],
            },
        ),
        migrations.CreateModel(
            name="LevelQuestionnaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answers", models.JSONField()),
                (
                    "estimated_level",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("submitted_at", models.DateTimeField()),
                (
                    "validated_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "validated_sigma",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "chestionar de nivel",
                "verbose_name_plural": "chestionare de nivel",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="RatingRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("computation", models.PositiveIntegerField()),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="league.leagueevent",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="league.leagueseason",
                    ),
                ),
            ],
            options={
                "verbose_name": "calcul de rating",
                "verbose_name_plural": "calcule de rating",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Standing",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "ladder",
                    models.CharField(
                        choices=[
                            ("doubles", "Dublu"),
                            ("singles", "Simplu"),
                            ("pairs", "Perechi"),
                        ],
                        max_length=10,
                    ),
                ),
                ("competitor_id", models.CharField(max_length=80)),
                ("mu", models.FloatField()),
                ("sigma", models.FloatField()),
                ("level", models.FloatField()),
                ("rank_index", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tier", models.CharField(blank=True, max_length=10)),
                ("division", models.CharField(blank=True, max_length=3)),
                ("lp", models.PositiveIntegerField(default=0)),
                ("total_lp", models.PositiveIntegerField(default=0)),
                ("placement_left", models.PositiveSmallIntegerField(default=0)),
                ("matches_played", models.PositiveIntegerField(default=0)),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("eligible", models.BooleanField(default=False)),
                ("last_match_at", models.DateTimeField(blank=True, null=True)),
                (
                    "player_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="league.leagueseason",
                    ),
                ),
            ],
            options={
                "verbose_name": "clasament",
                "verbose_name_plural": "clasamente",
                "ordering": ["season", "ladder", "position"],
            },
        ),
        migrations.AddConstraint(
            model_name="leagueseason",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="season_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="leagueseason",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("location",),
                name="one_active_season",
            ),
        ),
        migrations.AddConstraint(
            model_name="leagueseason",
            constraint=models.UniqueConstraint(
                fields=("location", "number"), name="season_number_once"
            ),
        ),
        migrations.AddIndex(
            model_name="leagueevent",
            index=models.Index(
                fields=["season", "at", "id"], name="league_leag_season__9999ef_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leagueevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind__in", ["match", "cancel"])),
                fields=("season", "kind", "ref"),
                name="league_event_match_once",
            ),
        ),
        migrations.AddIndex(
            model_name="ratingrecord",
            index=models.Index(
                fields=["season", "computation"], name="league_rati_season__39d53f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="standing",
            constraint=models.UniqueConstraint(
                fields=("season", "ladder", "competitor_id"), name="standing_once"
            ),
        ),
    ]
