# Generated by Django 5.2.17 on 2026-09-27 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from jungle.core.db import append_only


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_grid_and_duration_checks"),
        ("devices", "0002_romanian_labels"),
        ("league", "0001_initial"),
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("official", "Oficial de ligă"),
                            ("challenge", "Provocare"),
                            ("tournament", "Turneu"),
                        ],
                        default="official",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Scor propus"),
                            ("awaiting_payment", "Așteaptă plata"),
                            ("applied", "Aplicat"),
                            ("disputed", "Disputat"),
                            ("expired", "Expirat"),
                            ("cancelled", "Anulat"),
                            ("training", "Convertit în antrenament"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.JSONField()),
                (
                    "finished_at",
                    models.DateTimeField(
                        help_text="Finalul meciului: ordinea în ligă."
                    ),
                ),
                ("window_closes_at", models.DateTimeField()),
                ("proposed_at", models.DateTimeField()),
                ("payment_deadline", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "reopened_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Adminul a redeschis fereastra: scorul se reintroduce.",
                        null=True,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="league_matches",
                        to="bookings.booking",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match",
                        to="league.leagueevent",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="league.leagueseason",
                    ),
                ),
            ],
            options={
                "verbose_name": "meci de ligă",
                "verbose_name_plural": "meciuri de ligă",
                "ordering": ["-finished_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchPlayer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "side",
                    models.CharField(
                        choices=[("a", "Echipa A"), ("b", "Echipa B")], max_length=1
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("pending", "Așteaptă"),
                            ("confirmed", "Confirmat"),
                            ("disputed", "Contestat"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="devices.device",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="players",
                        to="league.leaguematch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "jucător în meci",
                "verbose_name_plural": "jucători în meci",
                "ordering": ["match", "side", "id"],
            },
        ),
        migrations.CreateModel(
            name="MatchTransition",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=20)),
                ("at", models.DateTimeField()),
                ("actor", models.JSONField(default=dict)),
                ("checks", models.JSONField(default=dict)),
                ("reason", models.CharField(blank=True, max_length=500)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="devices.device",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="league.leaguematch",
                    ),
                ),
            ],
            options={
                "verbose_name": "pas al meciului",
                "verbose_name_plural": "pașii meciurilor",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="leaguematch",
            index=models.Index(
                fields=["status", "window_closes_at"],
                name="league_leag_status_386c8d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaguematch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("booking",),
                name="one_live_match_per_booking",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchplayer",
            constraint=models.UniqueConstraint(
                fields=("match", "user"), name="match_player_once"
            ),
        ),
        # §6.16, LG-098: the league's history is never rewritten.
        *append_only("league_leagueevent"),
        *append_only("league_ratingrecord"),
        *append_only("league_matchtransition"),
    ]
