# Generated by Django 5.2.17 on 2026-09-27 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0002_matches"),
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ladder",
                    models.CharField(
                        choices=[
                            ("doubles", "Dublu"),
                            ("singles", "Simplu"),
                            ("pairs", "Perechi"),
                        ],
                        max_length=10,
                    ),
                ),
                ("challenger_rank", models.PositiveSmallIntegerField()),
                ("target_rank", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Așteaptă răspunsul"),
                            ("accepted", "Acceptată"),
                            ("refused", "Refuzată"),
                            ("expired", "Expirată"),
                            ("played", "Jucată"),
                            ("cancelled", "Anulată"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("respond_by", models.DateTimeField()),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("play_by", models.DateTimeField(blank=True, null=True)),
                ("refusal_outcome", models.CharField(blank=True, max_length=15)),
                (
                    "challenger_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenger_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="challenges",
                        to="league.leagueseason",
                    ),
                ),
                (
                    "target_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "provocare",
                "verbose_name_plural": "provocări",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="leaguematch",
            name="challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="league.challenge",
            ),
        ),
        migrations.CreateModel(
            name="DecayWarning",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("day", models.DateField()),
                (
                    "ladder",
                    models.CharField(
                        choices=[
                            ("doubles", "Dublu"),
                            ("singles", "Simplu"),
                            ("pairs", "Perechi"),
                        ],
                        max_length=10,
                    ),
                ),
                ("competitor_id", models.CharField(max_length=80)),
                ("sent_at", models.DateTimeField()),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="league.leagueseason",
                    ),
                ),
            ],
            options={
                "verbose_name": "avertizare de decay",
                "verbose_name_plural": "avertizări de decay",
            },
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["status", "respond_by"], name="league_chal_status_78183e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="decaywarning",
            constraint=models.UniqueConstraint(
                fields=("season", "day", "ladder", "competitor_id"),
                name="decay_warning_once",
            ),
        ),
    ]
