# Generated by Django 5.2.17 on 2026-09-27 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_grid_and_duration_checks"),
        ("league", "0003_challenges"),
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueseason",
            name="rewards",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Regulile recompenselor, fixate la început (LG-122).",
            ),
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=30)),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        help_text="Sezonul, săptămâna sau gol (o dată în viață).",
                        max_length=60,
                    ),
                ),
                ("awarded_at", models.DateTimeField()),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="league.leagueseason",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "insignă",
                "verbose_name_plural": "insigne",
                "ordering": ["-awarded_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "code", "key"), name="badge_once"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchOfTheDay",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("day", models.DateField()),
                ("reason", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="bookings.booking",
                    ),
                ),
                (
                    "chosen_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "meciul zilei",
                "verbose_name_plural": "meciurile zilei",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "day"), name="match_of_the_day_once"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SeasonAward",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("king", "Rege al Junglei (top 3)"),
                            ("tier_top", "Top 3 în rang"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ladder",
                    models.CharField(
                        choices=[
                            ("doubles", "Dublu"),
                            ("singles", "Simplu"),
                            ("pairs", "Perechi"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tier", models.CharField(max_length=10)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="1–3 în clasamentul final al rangului."
                    ),
                ),
                ("competitor_id", models.CharField(max_length=80)),
                ("vouchers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField()),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="league.leagueseason",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "premiu de sezon",
                "verbose_name_plural": "premii de sezon",
                "ordering": ["season", "kind", "tier", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("season", "kind", "ladder", "tier", "user"),
                        name="season_award_once",
                    )
                ],
            },
        ),
    ]
