# Generated by Django 5.2.17 on 2026-09-28 05:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_grid_and_duration_checks"),
        ("league", "0004_leagueseason_rewards_badge_matchoftheday_seasonaward"),
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("knockout", "Eliminatoriu"),
                            ("groups_knockout", "Grupe + eliminatoriu"),
                            ("round_robin", "Fiecare cu fiecare"),
                            ("americano", "Americano"),
                            ("mexicano", "Mexicano"),
                            ("king_of_the_court", "King of the Court"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "team_size",
                    models.PositiveSmallIntegerField(
                        help_text="Jucători pe echipă în meci: 1 sau 2."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registration", "Înscrieri deschise"),
                            ("in_progress", "În desfășurare"),
                            ("finished", "Încheiat"),
                            ("cancelled", "Anulat"),
                        ],
                        default="registration",
                        max_length=15,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("registration_closes_at", models.DateTimeField()),
                (
                    "entry_fee",
                    models.PositiveIntegerField(
                        help_text="Taxa de participare, în bani."
                    ),
                ),
                (
                    "fee_provisional",
                    models.BooleanField(default=True, help_text="DE_STABILIT (Q21)."),
                ),
                ("max_entries", models.PositiveSmallIntegerField()),
                (
                    "seeding",
                    models.CharField(
                        choices=[
                            ("rank", "După rang (LP)"),
                            ("random", "Tragere la sorți"),
                        ],
                        default="rank",
                        max_length=10,
                    ),
                ),
                ("draw_seed", models.CharField(blank=True, max_length=40)),
                ("group_size", models.PositiveSmallIntegerField(default=4)),
                (
                    "advance",
                    models.PositiveSmallIntegerField(
                        default=2, help_text="Calificați din fiecare grupă."
                    ),
                ),
                (
                    "rounds",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Mexicano, King of the Court."
                    ),
                ),
                (
                    "phase_bonuses",
                    models.JSONField(
                        default=dict, help_text="LP pe fază, fixate la creare."
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("drawn_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "turneu",
                "verbose_name_plural": "turnee",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="TournamentEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("registered", "Înscris"), ("withdrawn", "Retras")],
                        default="registered",
                        max_length=10,
                    ),
                ),
                ("seed", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("registered_at", models.DateTimeField()),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Locul final.", null=True
                    ),
                ),
                ("bonus_lp", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "înscriere la turneu",
                "verbose_name_plural": "înscrieri la turnee",
                "ordering": ["tournament", "seed", "registered_at"],
            },
        ),
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        help_text="group:A, round, semifinal, final …", max_length=20
                    ),
                ),
                ("round", models.PositiveSmallIntegerField()),
                ("slot", models.PositiveSmallIntegerField()),
                ("team_a", models.JSONField(blank=True, default=list)),
                ("team_b", models.JSONField(blank=True, default=list)),
                ("next_side", models.CharField(blank=True, max_length=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Așteaptă echipele"),
                            ("ready", "De jucat"),
                            ("finished", "Terminat, se introduce scorul"),
                            ("done", "Rezultat înregistrat"),
                            ("bye", "Calificare directă"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("winner", models.CharField(blank=True, max_length=1)),
                ("score", models.JSONField(blank=True, default=dict)),
                ("games_a", models.PositiveSmallIntegerField(default=0)),
                ("games_b", models.PositiveSmallIntegerField(default=0)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="bookings.booking",
                    ),
                ),
                (
                    "next_fixture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="league.fixture",
                    ),
                ),
            ],
            options={
                "verbose_name": "meci de turneu",
                "verbose_name_plural": "meciuri de turneu",
                "ordering": ["tournament", "round", "slot"],
            },
        ),
        migrations.AddField(
            model_name="leaguematch",
            name="fixture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="league_matches",
                to="league.fixture",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaguematch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("fixture",),
                name="one_live_match_per_fixture",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="locations.location"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tournaments",
                to="league.leagueseason",
            ),
        ),
        migrations.AddField(
            model_name="fixture",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixtures",
                to="league.tournament",
            ),
        ),
        migrations.AddField(
            model_name="tournamententry",
            name="player_a",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournamententry",
            name="player_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournamententry",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="league.tournament",
            ),
        ),
        migrations.AddField(
            model_name="fixture",
            name="entry_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="league.tournamententry",
            ),
        ),
        migrations.AddField(
            model_name="fixture",
            name="entry_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="league.tournamententry",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixture",
            constraint=models.UniqueConstraint(
                fields=("tournament", "phase", "round", "slot"), name="fixture_once"
            ),
        ),
    ]
