# Generated by Django 5.2.17 on 2026-09-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0005_tournaments"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonaward",
            name="choice",
            field=models.CharField(
                blank=True,
                help_text="Opțiunea aleasă în cont (Q6); gol: încă nealeasă.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="seasonaward",
            name="chosen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
