"""Stable API error codes (ADR-0018).

The API never returns user-facing text: it returns a code plus parameters, and every
interface translates the code from `packages/i18n` (`errors.<code>`). A test checks that
every code below has a Romanian and an English translation.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    # Generic
    VALIDATION_INVALID = "validation.invalid"
    NOT_FOUND = "common.not_found"
    FEATURE_DISABLED = "feature.disabled"
    # Authentication / authorization
    AUTH_REQUIRED = "auth.required"
    AUTH_FORBIDDEN = "auth.forbidden"
    AUTH_MFA_REQUIRED = "auth.mfa_required"
    AUTH_INVALID_CREDENTIALS = "auth.invalid_credentials"
    AUTH_LOCKED = "auth.locked"
    AUTH_MFA_CODE_REQUIRED = "auth.mfa_code_required"
    AUTH_MFA_CODE_INVALID = "auth.mfa_code_invalid"
    AUTH_CSRF_FAILED = "auth.csrf_failed"
    AUTH_RATE_LIMITED = "auth.rate_limited"
    MFA_ALREADY_ENABLED = "mfa.already_enabled"
    MFA_SETUP_NOT_STARTED = "mfa.setup_not_started"
    # Accounts
    ACCOUNTS_EMAIL_INVALID = "accounts.email_invalid"
    ACCOUNTS_EMAIL_TAKEN = "accounts.email_taken"
    ACCOUNTS_PHONE_INVALID = "accounts.phone_invalid"
    ACCOUNTS_PASSWORD_WEAK = "accounts.password_weak"
    ACCOUNTS_BIRTH_DATE_INVALID = "accounts.birth_date_invalid"
    ACCOUNTS_TOO_YOUNG = "accounts.too_young_for_self_registration"
    ACCOUNTS_TOKEN_INVALID = "accounts.token_invalid"
    ACCOUNTS_TOKEN_EXPIRED = "accounts.token_expired"
    ACCOUNTS_CURRENT_PASSWORD_INCORRECT = "accounts.current_password_incorrect"
    ACCOUNTS_GUARDIAN_NOT_ADULT = "accounts.guardian_not_adult"
    ACCOUNTS_CHILD_NOT_MINOR = "accounts.child_not_minor"
    ACCOUNTS_NOT_FOUND = "accounts.not_found"
    ROLES_ALREADY_GRANTED = "roles.already_granted"
    ROLES_NOT_FOUND = "roles.not_found"
    ROLES_LAST_ADMIN = "roles.last_admin"
    # Configuration
    FLAGS_UNKNOWN = "flags.unknown"
    CONFIG_UNKNOWN_KEY = "config.unknown_key"
    CONFIG_INVALID_VALUE = "config.invalid_value"
    # Legal
    LEGAL_DOCUMENT_UNAVAILABLE = "legal.document_unavailable"
    LEGAL_CONSENT_MISSING = "legal.consent_missing"
    LEGAL_CONSENT_OUTDATED = "legal.consent_outdated"
    # Locations, resources, devices
    LOCATIONS_NOT_FOUND = "locations.not_found"
    LOCATIONS_SLUG_TAKEN = "locations.slug_taken"
    RESOURCES_NOT_FOUND = "resources.not_found"
    RESOURCES_SLUG_TAKEN = "resources.slug_taken"
    RESOURCES_INVALID_PARENT = "resources.invalid_parent"
    RESOURCES_INVALID_CAPACITY = "resources.invalid_capacity"
    DEVICES_NOT_FOUND = "devices.not_found"
    # Bookings (Stage 3)
    BOOKING_NOT_FOUND = "booking.not_found"
    BOOKING_EMAIL_NOT_VERIFIED = "booking.email_not_verified"
    BOOKING_SLOT_TAKEN = "booking.slot_taken"
    BOOKING_INVALID_DURATION = "booking.invalid_duration"
    BOOKING_OFF_GRID = "booking.off_grid"
    BOOKING_OUTSIDE_HOURS = "booking.outside_hours"
    BOOKING_IN_PAST = "booking.in_past"
    BOOKING_RESTRICTED = "booking.restricted"
    BOOKING_RESOURCE_NOT_BOOKABLE = "booking.resource_not_bookable"
    BOOKING_NOT_CANCELLABLE = "booking.not_cancellable"
    BOOKING_NOT_MOVABLE = "booking.not_movable"
    BOOKING_TYPE_LOCKED = "booking.type_locked"
    BOOKING_INVALID_TYPE = "booking.invalid_type"
    BOOKING_COACH_REQUIRED = "booking.coach_required"
    BOOKING_COACH_BUSY = "booking.coach_busy"
    BOOKING_ALREADY_WAITING = "booking.already_waiting"
    PRICING_RATE_MISSING = "pricing.rate_missing"
    CLASSES_NOT_FOUND = "classes.not_found"
    CLASSES_ALREADY_ENROLLED = "classes.already_enrolled"
    CLASSES_CAPACITY_TOO_HIGH = "classes.capacity_too_high"
    CLASSES_NOT_CANCELLABLE = "classes.not_cancellable"
    CLASSES_STUDIO_BUSY = "classes.studio_busy"
    EVENTS_NOT_FOUND = "events.not_found"
    EVENTS_TOO_MANY_GUESTS = "events.too_many_guests"
    EVENTS_ALREADY_DECIDED = "events.already_decided"
    EVENTS_EVENT_NOT_FOUND = "events.event_not_found"
    EVENTS_INVALID_TIME = "events.invalid_time"
    EVENTS_ALREADY_CANCELLED = "events.already_cancelled"
    BLOG_NOT_FOUND = "blog.not_found"
    BLOG_SLUG_TAKEN = "blog.slug_taken"
    BLOG_SLUG_LOCKED = "blog.slug_locked"
    BLOG_ALREADY_PUBLISHED = "blog.already_published"
    NOTIFICATIONS_NOT_OPTIONAL = "notifications.not_optional"
    NOTIFICATIONS_PUSH_UNAVAILABLE = "notifications.push_unavailable"
    NOTIFICATIONS_UNKNOWN = "notifications.unknown"
    NOTIFICATIONS_TEMPLATE_INVALID = "notifications.template_invalid"
    # The AI (ADR-0019)
    AI_FORBIDDEN = "ai.forbidden"
    AI_UNAVAILABLE = "ai.unavailable"
    AI_NOT_CONFIGURED = "ai.not_configured"
    ATTENDANCE_UNKNOWN_PERSON = "attendance.unknown_person"
    RESTRICTIONS_NOT_FOUND = "restrictions.not_found"
    PAYMENTS_IDEMPOTENCY_REQUIRED = "payments.idempotency_required"
    PAYMENTS_IDEMPOTENCY_CONFLICT = "payments.idempotency_conflict"
    PAYMENTS_INVALID_AMOUNT = "payments.invalid_amount"
    PAYMENTS_NOTHING_DUE = "payments.nothing_due"
    PAYMENTS_OVERPAY = "payments.overpay"
    PAYMENTS_INSUFFICIENT_CASH = "payments.insufficient_cash"
    PAYMENTS_INSUFFICIENT_BALANCE = "payments.insufficient_balance"
    PAYMENTS_METHOD_UNAVAILABLE = "payments.method_unavailable"
    LEDGER_NOT_FOUND = "ledger.not_found"
    LEDGER_ALREADY_REVERSED = "ledger.already_reversed"
    LEDGER_CANNOT_REVERSE = "ledger.cannot_reverse"
    # Waitlist
    WAITLIST_TOKEN_INVALID = "waitlist.token_invalid"
    WAITLIST_TOKEN_EXPIRED = "waitlist.token_expired"
    SUBSCRIPTIONS_NOT_FOUND = "subscriptions.not_found"
    SUBSCRIPTIONS_INVALID_SELECTION = "subscriptions.invalid_selection"
    SUBSCRIPTIONS_INVALID_START = "subscriptions.invalid_start"
    SUBSCRIPTIONS_NOT_CANCELLABLE = "subscriptions.not_cancellable"
    SUBSCRIPTIONS_NOT_ACTIVE = "subscriptions.not_active"
    SUBSCRIPTIONS_FREEZE_LIMIT = "subscriptions.freeze_limit"
    SUBSCRIPTIONS_FREEZE_OVERLAP = "subscriptions.freeze_overlap"
    SUBSCRIPTIONS_FREEZE_CONFLICT = "subscriptions.freeze_conflict"
    CORPORATE_NOT_FOUND = "corporate.not_found"
    CORPORATE_NOT_MEMBER = "corporate.not_member"
    CORPORATE_ALREADY_MEMBER = "corporate.already_member"
    VOUCHERS_NOT_FOUND = "vouchers.not_found"
    VOUCHERS_NOT_VALID = "vouchers.not_valid"
    VOUCHERS_WRONG_TARGET = "vouchers.wrong_target"
    VOUCHERS_BAND_NOT_ALLOWED = "vouchers.band_not_allowed"
    REFERRALS_INVALID_CODE = "referrals.invalid_code"
    REFERRALS_SELF = "referrals.self"
    REFERRALS_ALREADY_CLAIMED = "referrals.already_claimed"
    REFERRALS_NOT_NEW = "referrals.not_new"
    CAFE_PRODUCT_UNAVAILABLE = "cafe.product_unavailable"
    CAFE_ORDER_NOT_FOUND = "cafe.order_not_found"
    CAFE_INVALID_TRANSITION = "cafe.invalid_transition"
    CAFE_EMPTY_ORDER = "cafe.empty_order"
    CARDS_NOT_FOUND = "cards.not_found"
    CARDS_INVALID = "cards.invalid"
    CARDS_NOTHING_TO_PRINT = "cards.nothing_to_print"
    CARDS_INVALID_TRANSITION = "cards.invalid_transition"
    CARDS_INVALID_EMBLEM = "cards.invalid_emblem"
    WALLET_UNAVAILABLE = "wallet.unavailable"
    LEAGUE_KIOSK_ONLY = "league.kiosk_only"
    LEAGUE_ADULTS_ONLY = "league.adults_only"
    PRIVACY_NO_CONSENT = "privacy.no_consent"
    PRIVACY_STAFF_ACCOUNT = "privacy.staff_account"
    PRIVACY_HAS_CHILDREN = "privacy.has_children"
    PRIVACY_OUTSTANDING_DEBT = "privacy.outstanding_debt"
    PRIVACY_CREDIT_LEFT = "privacy.credit_left"
    PRIVACY_FUTURE_BOOKINGS = "privacy.future_bookings"
    PRIVACY_WRONG_PASSWORD = "privacy.wrong_password"
    LEAGUE_ALREADY_PLAYING = "league.already_playing"
    LEAGUE_BONUS_NOT_APPLICABLE = "league.bonus_not_applicable"
    LEAGUE_DAILY_LIMIT = "league.daily_limit"
    LEAGUE_DUPLICATE_PLAYER = "league.duplicate_player"
    LEAGUE_INVALID_PLAYER_ID = "league.invalid_player_id"
    LEAGUE_NAIVE_DATETIME = "league.naive_datetime"
    LEAGUE_OUT_OF_ORDER = "league.out_of_order"
    LEAGUE_TEAM_SIZE = "league.team_size"
    LEAGUE_UNKNOWN_PLAYER = "league.unknown_player"
    LEAGUE_SCORE_IMPOSSIBLE_SET = "league.score_impossible_set"
    LEAGUE_SCORE_MARKED_UNFINISHED_BUT_WON = "league.score_marked_unfinished_but_won"
    LEAGUE_SCORE_MATCH_NOT_FINISHED = "league.score_match_not_finished"
    LEAGUE_SCORE_NEGATIVE = "league.score_negative"
    LEAGUE_SCORE_SET_AFTER_MATCH_WON = "league.score_set_after_match_won"
    LEAGUE_SCORE_SET_COUNT = "league.score_set_count"
    LEAGUE_SCORE_SET_NOT_FINISHED = "league.score_set_not_finished"
    LEAGUE_SCORE_SUPER_TIEBREAK_NOT_ALLOWED = "league.score_super_tiebreak_not_allowed"
    LEAGUE_SCORE_SUPER_TIEBREAK_REQUIRED = "league.score_super_tiebreak_required"
    LEAGUE_SCORE_TIEBREAK_INVALID = "league.score_tiebreak_invalid"
    LEAGUE_SCORE_TIEBREAK_MISSING = "league.score_tiebreak_missing"
    LEAGUE_NO_ACTIVE_SEASON = "league.no_active_season"
    LEAGUE_NOT_ELIGIBLE = "league.not_eligible"
    LEAGUE_QUESTIONNAIRE_INVALID = "league.questionnaire_invalid"
    LEAGUE_QUESTIONNAIRE_NOT_FOUND = "league.questionnaire_not_found"
    LEAGUE_SEASON_INVALID = "league.season_invalid"
    LEAGUE_MATCH_NOT_FOUND = "league.match_not_found"
    LEAGUE_SCORE_KIOSK_ONLY = "league.score_kiosk_only"
    LEAGUE_WINDOW_NOT_OPEN = "league.window_not_open"
    LEAGUE_WINDOW_CLOSED = "league.window_closed"
    LEAGUE_BOOKING_NOT_ELIGIBLE = "league.booking_not_eligible"
    LEAGUE_PLAYERS_NOT_SCANNED = "league.players_not_scanned"
    LEAGUE_PLAYER_NOT_IN_LEAGUE = "league.player_not_in_league"
    LEAGUE_NOT_A_PLAYER = "league.not_a_player"
    LEAGUE_SCORE_ALREADY_PROPOSED = "league.score_already_proposed"
    LEAGUE_ALREADY_RESPONDED = "league.already_responded"
    LEAGUE_MATCH_NOT_OPEN = "league.match_not_open"
    LEAGUE_MATCH_STATE_INVALID = "league.match_state_invalid"
    LEAGUE_REASON_REQUIRED = "league.reason_required"
    LEAGUE_CHALLENGE_NOT_ALLOWED = "league.challenge_not_allowed"
    LEAGUE_CHALLENGE_NOT_RANKED = "league.challenge_not_ranked"
    LEAGUE_CHALLENGE_EXISTS = "league.challenge_exists"
    LEAGUE_CHALLENGE_NOT_FOUND = "league.challenge_not_found"
    LEAGUE_CHALLENGE_NOT_TARGET = "league.challenge_not_target"
    LEAGUE_CHALLENGE_REQUIRED = "league.challenge_required"
    LEAGUE_SEASON_NOT_OVER = "league.season_not_over"
    LEAGUE_SEASON_OPEN_MATCHES = "league.season_open_matches"
    LEAGUE_NOT_A_MATCH_TODAY = "league.not_a_match_today"
    LEAGUE_TOURNAMENT_NOT_FOUND = "league.tournament_not_found"
    LEAGUE_TOURNAMENT_INVALID = "league.tournament_invalid"
    LEAGUE_TOURNAMENT_CLOSED = "league.tournament_closed"
    LEAGUE_TOURNAMENT_FULL = "league.tournament_full"
    LEAGUE_TOURNAMENT_ALREADY_ENTERED = "league.tournament_already_entered"
    LEAGUE_TOURNAMENT_PARTNER = "league.tournament_partner"
    LEAGUE_TOURNAMENT_TOO_FEW = "league.tournament_too_few"
    LEAGUE_FIXTURE_NOT_FOUND = "league.fixture_not_found"
    LEAGUE_FIXTURE_NOT_READY = "league.fixture_not_ready"
    LEAGUE_FIXTURE_NOT_SCHEDULED = "league.fixture_not_scheduled"
    LEAGUE_REWARD_NOT_FOUND = "league.reward_not_found"
    LEAGUE_REWARD_OPTION_INVALID = "league.reward_option_invalid"
    DEVICES_AUTH_FAILED = "devices.auth_failed"
    DEVICES_SIGNATURE_INVALID = "devices.signature_invalid"
    DEVICES_KEY_INVALID = "devices.key_invalid"
    DEVICES_SESSION_EXPIRED = "devices.session_expired"
    # Screens: the teams chosen at the League Kiosk (Q55)
    SCREENS_NOT_ON_COURT = "screens.not_on_court"
    SCREENS_TEAMS_FIXED = "screens.teams_fixed"
    LEAGUE_SCORE_TOURNAMENT_UNFINISHED = "league.score_tournament_unfinished"
    LEAGUE_JOINED_AFTER_MATCH = "league.joined_after_match"
    CHECKOUT_KIOSK_ONLY = "checkout.kiosk_only"
    CHECKOUT_BUSY = "checkout.busy"
    CHECKOUT_NOT_FOUND = "checkout.not_found"
    CHECKOUT_STATE_INVALID = "checkout.state_invalid"
    CHECKOUT_NOT_YOURS = "checkout.not_yours"
    CHECKOUT_EMPTY = "checkout.empty"
    CHECKOUT_TOO_MUCH = "checkout.too_much"
    CHECKOUT_DUPLICATE_ITEM = "checkout.duplicate_item"
    CHECKOUT_WRONG_LOCATION = "checkout.wrong_location"
    CHECKOUT_EXACT_IMPOSSIBLE = "checkout.exact_impossible"
    CHECKOUT_STALE = "checkout.stale"
    CHECKOUT_NOT_ENOUGH = "checkout.not_enough"
    CHECKOUT_WAITING_CHANGE = "checkout.waiting_change"
    CHECKOUT_EVENT_INVALID = "checkout.event_invalid"
    CHECKOUT_PIN_FORMAT = "checkout.pin_format"
    CHECKOUT_PIN_WRONG = "checkout.pin_wrong"
    CHECKOUT_PIN_LOCKED = "checkout.pin_locked"
    CHECKOUT_STAFF_ONLY = "checkout.staff_only"
    CHECKOUT_OPERATION_INVALID = "checkout.operation_invalid"
    CHECKOUT_OPERATION_NOT_FOUND = "checkout.operation_not_found"


class DomainError(Exception):
    """A business-rule violation, returned to clients as `{"error": {"code", "params"}}`."""

    def __init__(self, code: ErrorCode, status: int = 400, params: dict[str, Any] | None = None):
        super().__init__(code.value)
        self.code = code
        self.status = status
        self.params = params or {}
