# Generated by Django 5.2.17 on 2026-10-06 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("public", "Asistent public (fără cont)"),
                            ("member", "Asistent în contul clientului"),
                            ("staff", "Copilot pentru personal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model", models.CharField(max_length=80)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("answered", "Răspuns"),
                            ("refused", "Refuzat de model"),
                            ("budget", "Limita lunară atinsă"),
                            ("steps", "Prea mulți pași"),
                            ("failed", "Eroare la furnizor"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tools", models.JSONField(default=list)),
                ("steps", models.PositiveSmallIntegerField(default=0)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_micro_usd",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="cost (milionimi de dolar)"
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_interactions",
                        to="locations.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "interacțiune AI",
                "verbose_name_plural": "interacțiuni AI",
                "indexes": [
                    models.Index(fields=["created_at"], name="ai_interaction_by_time")
                ],
            },
        ),
    ]
