# Generated by Django 5.2.17 on 2026-10-06 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("community", "Mesaj pentru comunitate"),
                            ("article", "Articol"),
                            ("translation", "Traducere"),
                        ],
                        max_length=12,
                    ),
                ),
                ("language", models.CharField(max_length=2)),
                ("request", models.TextField(max_length=8000, verbose_name="cererea")),
                ("body", models.TextField(max_length=20000, verbose_name="textul")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_review", "De revizuit"),
                            ("approved", "Aprobată"),
                            ("discarded", "Renunțat"),
                        ],
                        default="to_review",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "interaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ai.aiinteraction",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_drafts",
                        to="locations.location",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ciornă AI",
                "verbose_name_plural": "ciorne AI",
                "ordering": ["-created_at"],
            },
        ),
    ]
