# Generated by Django 5.2.17 on 2026-09-26 20:54

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_kind",
                    models.CharField(
                        choices=[
                            ("user", "Utilizator"),
                            ("device", "Dispozitiv"),
                            ("system", "Sistem"),
                            ("ai", "AI"),
                            ("anonymous", "Anonim"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "actor_user_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("actor_device_id", models.UUIDField(blank=True, null=True)),
                ("actor_label", models.CharField(blank=True, max_length=200)),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("target_type", models.CharField(blank=True, max_length=60)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                (
                    "before",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "after",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "verbose_name": "înregistrare de audit",
                "verbose_name_plural": "jurnal de audit",
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_audit_target__2d648a_idx",
                    )
                ],
            },
        ),
    ]
