# Generated by Django 5.2.17 on 2026-09-27 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0002_romanian_labels"),
        ("ledger", "0004_longer_account_category"),
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CafeCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_ro", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "categorie cafenea",
                "verbose_name_plural": "categorii cafenea",
                "ordering": ["sort_order", "name_ro"],
            },
        ),
        migrations.CreateModel(
            name="CafeOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        help_text="Ziua (ora României) pentru numerotare."
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Numărul comenzii din ziua respectivă."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouă"),
                            ("preparing", "În preparare"),
                            ("ready", "Gata"),
                            ("picked_up", "Ridicată"),
                            ("cancelled", "Anulată"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("total", models.PositiveIntegerField(verbose_name="total (bani)")),
                ("created_at", models.DateTimeField()),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.device",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.ledgertransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "comandă cafenea",
                "verbose_name_plural": "comenzi cafenea",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CafeProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_ro", models.CharField(max_length=120)),
                ("name_en", models.CharField(max_length=120)),
                ("price", models.PositiveIntegerField(verbose_name="preț (bani)")),
                (
                    "marker",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmat de proprietar"),
                            ("default", "Valoare tehnică implicită"),
                            ("to_confirm", "DE_CONFIRMAT"),
                            ("to_set", "DE_STABILIT"),
                        ],
                        default="to_set",
                        max_length=12,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="cafe.cafecategory",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "produs cafenea",
                "verbose_name_plural": "produse cafenea",
                "ordering": ["sort_order", "name_ro"],
            },
        ),
        migrations.CreateModel(
            name="CafeOrderLine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Numele la momentul comenzii.", max_length=120
                    ),
                ),
                ("unit_price", models.PositiveIntegerField()),
                ("quantity", models.PositiveSmallIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="cafe.cafeorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cafe.cafeproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "produs comandat",
                "verbose_name_plural": "produse comandate",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="cafeorder",
            constraint=models.UniqueConstraint(
                fields=("location", "day", "number"), name="cafe_order_number_per_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="cafeorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="cafe_line_quantity"
            ),
        ),
    ]
