# Generated by Django 5.2.17 on 2026-09-30 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dj_night", "Seară cu DJ"),
                            ("social", "Padel social (Americano, Mexicano)"),
                            ("club", "Eveniment al clubului"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title_ro", models.CharField(max_length=120)),
                ("title_en", models.CharField(max_length=120)),
                ("text_ro", models.CharField(blank=True, max_length=500)),
                ("text_en", models.CharField(blank=True, max_length=500)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("published", models.BooleanField(default=False)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=500)),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="club_events",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "eveniment în calendar",
                "verbose_name_plural": "calendarul evenimentelor",
                "ordering": ["starts_at"],
                "indexes": [
                    models.Index(
                        fields=["location", "starts_at"], name="club_event_by_start"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="club_event_ends_after_start",
                    )
                ],
            },
        ),
    ]
