# Generated by Django 5.2.17 on 2026-09-27 12:58

import django.contrib.postgres.constraints
import django.db.models.deletion
import jungle.bookings.models
import uuid
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="început")),
                ("ends_at", models.DateTimeField(verbose_name="sfârșit")),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("official_match", "Meci oficial de ligă"),
                            ("training", "Antrenament / amical"),
                            ("lesson", "Lecție cu antrenor"),
                            ("tournament", "Turneu"),
                            ("challenge", "Provocare"),
                            ("free_rental", "Închiriere liberă"),
                            ("event", "Eveniment"),
                        ],
                        max_length=20,
                        verbose_name="tip sesiune",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmată"),
                            ("cancelled", "Anulată"),
                            ("completed", "Încheiată"),
                            ("no_show", "Neprezentare"),
                        ],
                        default="confirmed",
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("reception", "Recepție"),
                            ("kiosk", "Chioșc"),
                            ("waitlist", "Lista de așteptare"),
                            ("event_request", "Cerere de eveniment"),
                        ],
                        default="online",
                        max_length=15,
                    ),
                ),
                ("customer_type", models.CharField(default="standard", max_length=12)),
                (
                    "price_total",
                    models.PositiveIntegerField(verbose_name="preț (bani)"),
                ),
                ("price_breakdown", models.JSONField(default=dict)),
                (
                    "price_provisional",
                    models.BooleanField(
                        default=False, help_text="Tarif DE_STABILIT (Q21)."
                    ),
                ),
                (
                    "promoted_at",
                    models.DateTimeField(
                        blank=True, help_text="Intrat de pe listă.", null=True
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("free", "Gratuită (eligibilă pentru recuperare)"),
                            ("charged", "Se plătește"),
                            ("waived", "Scutită de personal (cu motiv)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cancellation_reason", models.CharField(blank=True, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coached_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="locations.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "rezervare",
                "verbose_name_plural": "rezervări",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("beginner", "Începători"),
                            ("intermediate", "Intermediar"),
                            ("advanced", "Avansat"),
                            ("private", "Ședință privată"),
                            ("duo", "Duo"),
                            ("group", "Grup"),
                            (
                                "racket_players",
                                "Reformer pentru jucători de tenis/padel",
                            ),
                            ("mothers", "Reformer pentru mămici"),
                        ],
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("capacity", models.PositiveSmallIntegerField()),
                (
                    "price_total",
                    models.PositiveIntegerField(verbose_name="preț pe persoană (bani)"),
                ),
                ("price_provisional", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("scheduled", "Programată"), ("cancelled", "Anulată")],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="taught_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_sessions",
                        to="locations.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "clasă",
                "verbose_name_plural": "clase",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Înscris"),
                            ("waitlisted", "Pe lista de așteptare"),
                            ("cancelled", "Anulat"),
                            ("attended", "Prezent"),
                            ("no_show", "Neprezentare"),
                        ],
                        max_length=12,
                    ),
                ),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("free", "Gratuită (eligibilă pentru recuperare)"),
                            ("charged", "Se plătește"),
                            ("waived", "Scutită de personal (cu motiv)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="bookings.classsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "înscriere la clasă",
                "verbose_name_plural": "înscrieri la clase",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("guests", models.PositiveSmallIntegerField()),
                ("message", models.TextField(blank=True, max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "În așteptare"),
                            ("approved", "Aprobată"),
                            ("declined", "Respinsă"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bookings.booking",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "cerere de eveniment",
                "verbose_name_plural": "cereri de evenimente",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="SlotWaitlistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("official_match", "Meci oficial de ligă"),
                            ("training", "Antrenament / amical"),
                            ("lesson", "Lecție cu antrenor"),
                            ("tournament", "Turneu"),
                            ("challenge", "Provocare"),
                            ("free_rental", "Închiriere liberă"),
                            ("event", "Eveniment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Q4: abonații pot avea prioritate."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "În așteptare"),
                            ("promoted", "Intrat automat"),
                            ("cancelled", "Retras"),
                            ("expired", "Expirat"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.booking",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "loc pe lista de așteptare",
                "verbose_name_plural": "lista de așteptare (terenuri)",
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["location", "starts_at"], name="bookings_bo_locatio_d50606_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="booking_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                expressions=[
                    ("resource", "="),
                    (jungle.bookings.models.TsTzRange("starts_at", "ends_at"), "&&"),
                ],
                name="booking_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(
                    ("coach__isnull", False),
                    models.Q(("status", "cancelled"), _negated=True),
                ),
                expressions=[
                    ("coach", "="),
                    (jungle.bookings.models.TsTzRange("starts_at", "ends_at"), "&&"),
                ],
                name="booking_coach_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="classsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="class_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="classsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gte", 1)), name="class_capacity"
            ),
        ),
        migrations.AddConstraint(
            model_name="classsession",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                expressions=[
                    ("studio", "="),
                    (jungle.bookings.models.TsTzRange("starts_at", "ends_at"), "&&"),
                ],
                name="class_studio_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="classenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["enrolled", "waitlisted", "attended", "no_show"])
                ),
                fields=("session", "user"),
                name="class_one_active_enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="slotwaitlistentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "waiting")),
                fields=("user", "resource", "starts_at"),
                name="slot_waitlist_one_per_user",
            ),
        ),
    ]
