# Generated by Django 5.2.17 on 2026-09-27 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_grid_and_duration_checks"),
        ("devices", "0002_romanian_labels"),
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=120, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cash", "Numerar (casierie / chioșc)"),
                            ("card", "Card (POS / online)"),
                            ("receivable", "Datorii ale clientului"),
                            ("customer_balance", "Sold (credit) al clientului"),
                            ("vouchers", "Vouchere emise"),
                            ("revenue", "Venituri"),
                            ("discounts", "Reduceri și recompense acordate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=20)),
                ("currency", models.CharField(default="RON", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "cont contabil",
                "verbose_name_plural": "conturi contabile",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("charge", "Sumă datorată (rezervare, clasă, taxă)"),
                            ("payment", "Plată"),
                            ("credit", "Credit în cont"),
                            ("refund", "Rambursare"),
                            ("reversal", "Corecție (înregistrare inversă)"),
                            ("sale", "Vânzare (abonament, cafenea)"),
                            ("voucher_issue", "Voucher emis"),
                            ("voucher_redeem", "Voucher folosit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("request_hash", models.CharField(blank=True, max_length=64)),
                ("description", models.CharField(max_length=250)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("actor", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="bookings.booking",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="bookings.classenrollment",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="ledger.ledgertransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "tranzacție",
                "verbose_name_plural": "tranzacții",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.BigIntegerField(help_text="bani; + debit, − credit")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="ledger.ledgeraccount",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="ledger.ledgertransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "înregistrare",
                "verbose_name_plural": "înregistrări",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Numerar"),
                            ("card", "Card"),
                            ("balance", "Sold în cont"),
                            ("voucher", "Voucher"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.PositiveBigIntegerField()),
                ("tendered", models.PositiveBigIntegerField(default=0)),
                ("change", models.PositiveBigIntegerField(default=0)),
                ("fiscal_receipt", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField()),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="devices.device",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ledger.ledgertransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "plată",
                "verbose_name_plural": "plăți",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["booking"], name="ledger_ledg_booking_0b0377_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["enrollment"], name="ledger_ledg_enrollm_987a14_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="ledger_entry_not_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("change__lte", models.F("tendered"))),
                name="payment_change_le_tendered",
            ),
        ),
    ]
