# Generated by Django 5.2.17 on 2026-09-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_append_only_and_balanced"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgertransaction",
            name="subject",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
