# Generated by Django 5.2.17 on 2026-09-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_transaction_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgeraccount",
            name="category",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
