# Generated by Django 5.2.17 on 2026-09-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_longer_account_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgertransaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("charge", "Sumă datorată (rezervare, clasă, taxă)"),
                    ("payment", "Plată"),
                    ("credit", "Credit în cont"),
                    ("refund", "Rambursare"),
                    ("reversal", "Corecție (înregistrare inversă)"),
                    ("sale", "Vânzare (abonament, cafenea)"),
                    ("voucher_issue", "Voucher emis"),
                    ("voucher_redeem", "Voucher folosit"),
                    ("transfer", "Mutare de numerar (seif ↔ chioșc)"),
                ],
                max_length=20,
            ),
        ),
    ]
