# Generated by Django 5.2.17 on 2026-09-26 20:54

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "key",
                    models.CharField(max_length=60, primary_key=True, serialize=False),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "feature flag",
                "verbose_name_plural": "feature flags",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ConfigVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=80)),
                ("version", models.PositiveIntegerField()),
                (
                    "value",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "marker",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmat de proprietar"),
                            ("default", "Valoare tehnică implicită"),
                            ("to_confirm", "DE_CONFIRMAT"),
                            ("to_set", "DE_STABILIT"),
                        ],
                        max_length=12,
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "versiune de configurare",
                "verbose_name_plural": "versiuni de configurare",
                "ordering": ["key", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "version"), name="config_key_version_unique"
                    )
                ],
            },
        ),
    ]
