# Generated by Django 5.2.17 on 2026-09-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0002_append_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="enabled",
            field=models.BooleanField(default=False, verbose_name="activ"),
        ),
    ]
