# Generated by Django 5.2.17 on 2026-10-06 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_grid_and_duration_checks"),
        ("locations", "0002_romanian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asked_at", models.DateTimeField()),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bookings.booking",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "părere (NPS)",
                "verbose_name_plural": "păreri (NPS)",
                "ordering": ["-asked_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("score__isnull", True), ("score__lte", 10), _connector="OR"
                        ),
                        name="feedback_score_0_10",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("answered_at__isnull", True), ("score__isnull", True)
                            ),
                            models.Q(
                                ("answered_at__isnull", False), ("score__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="feedback_answered_with_score",
                    ),
                ],
            },
        ),
    ]
