# Generated by Django 5.2.17 on 2026-09-26 20:54

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="prenume"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="nume")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefon (E.164)"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="data nașterii"
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("ro", "Română"), ("en", "English")],
                        default="ro",
                        max_length=5,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("full", "Cont complet"),
                            ("guest", "Cont rapid (invitat)"),
                            ("child", "Cont de copil (gestionat de părinte)"),
                        ],
                        default="full",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="Date demo (seed), nu clienți reali."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "totp_secret",
                    models.TextField(blank=True, help_text="Criptat (Fernet)."),
                ),
                ("totp_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("totp_last_step", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "utilizator",
                "verbose_name_plural": "utilizatori",
                "ordering": ["last_name", "first_name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        condition=models.Q(("email__isnull", False)),
                        name="user_email_ci_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email__isnull", False),
                            ("account_type", "child"),
                            _connector="OR",
                        ),
                        name="user_email_required_unless_child",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MfaRecoveryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuardianLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("guardian", "child"), name="guardian_child_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("reception", "Recepție"),
                            ("coach", "Antrenor / Instructor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "rol",
                "verbose_name_plural": "roluri",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role", "location"),
                        name="user_role_unique",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
