# Generated by Django 5.2.17 on 2026-09-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guardianlink",
            options={
                "verbose_name": "legătură părinte–copil",
                "verbose_name_plural": "legături părinte–copil",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("full", "Cont complet"),
                    ("guest", "Cont rapid (invitat)"),
                    ("child", "Cont de copil (gestionat de părinte)"),
                ],
                default="full",
                max_length=10,
                verbose_name="tip cont",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creat la"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="email verificat la"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="activ"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                help_text="Date demo (seed), nu clienți reali.",
                verbose_name="demo",
            ),
        ),
    ]
