# Generated by Django 5.2.17 on 2026-09-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_romanian_labels"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="user_email_required_unless_child",
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="§12.2: datele personale au fost șterse; rămâne „Jucător retras”.",
                null=True,
                verbose_name="șters la",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email__isnull", False),
                    ("account_type", "child"),
                    ("deleted_at__isnull", False),
                    _connector="OR",
                ),
                name="user_email_required_unless_child_or_deleted",
            ),
        ),
    ]
